{% set name = "distmetrics" %}
{% set version = "1.0.7" %}
{% set python_min = "3.12" %} 

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/15/0a/26ddc951d6f594ad1581cfe7ca66a46fb0cb9796000c2e25b644df0aaa56/distmetrics-{{ version }}.tar.gz
  sha256: 7b8f95ccd779449dca059bc98c6a486a2c8f81dc93ded7c7851cb3e6b4d2d741

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - affine
    - rasterio
    - numpy
    - dem_stitcher
    - scikit-image
    - matplotlib-base
    - scipy
    - pydantic
    - astropy-base
    - einops
    - backoff
    - asf_search
    - shapely
    - geopandas
    - pytorch
    - pydantic
    - asf_search
    - tqdm
    - pandas

test:
  imports:
    - distmetrics
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/opera-adt/distmetrics
  summary: Measure Disturbances in OPERA RTC-S1 Stacks
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - richw7185
    - cmarshak
    - taliboliver
